import type { BootstrapData, Fixtures } from '@/types/fpl'

export const mockTeams: BootstrapData['teams'] = [
	{
		id: 1,
		name: 'Arsenal',
		short_name: 'ARS',
		strength: 4,
		strength_overall_home: 1250,
		strength_overall_away: 1300,
		strength_attack_home: 1200,
		strength_attack_away: 1250,
		strength_defence_home: 1300,
		strength_defence_away: 1350,
		pulse_id: 1,
		code: 3,
		form: '3.2',
	},
	{
		id: 2,
		name: 'Man City',
		short_name: 'MCI',
		strength: 5,
		strength_overall_home: 1350,
		strength_overall_away: 1400,
		strength_attack_home: 1350,
		strength_attack_away: 1400,
		strength_defence_home: 1350,
		strength_defence_away: 1400,
		pulse_id: 11,
		code: 11,
		form: '4.1',
	},
	{
		id: 3,
		name: 'Chelsea',
		short_name: 'CHE',
		strength: 4,
		strength_overall_home: 1200,
		strength_overall_away: 1250,
		strength_attack_home: 1150,
		strength_attack_away: 1200,
		strength_defence_home: 1250,
		strength_defence_away: 1300,
		pulse_id: 4,
		code: 8,
		form: '2.8',
	},
]

export const mockFixtures: Fixtures = [
	{
		id: 1,
		event: 1,
		team_h: 1,
		team_a: 2,
		team_h_difficulty: 4,
		team_a_difficulty: 2,
		kickoff_time: '2024-08-17T14:00:00Z',
		started: false,
		finished: false,
		team_h_score: null,
		team_a_score: null,
	},
	{
		id: 2,
		event: 2,
		team_h: 2,
		team_a: 1,
		team_h_difficulty: 3,
		team_a_difficulty: 5,
		kickoff_time: '2024-08-24T14:00:00Z',
		started: false,
		finished: false,
		team_h_score: null,
		team_a_score: null,
	},
	{
		id: 3,
		event: 1,
		team_h: 3,
		team_a: 1,
		team_h_difficulty: 3,
		team_a_difficulty: 4,
		kickoff_time: '2024-08-18T14:00:00Z',
		started: false,
		finished: false,
		team_h_score: null,
		team_a_score: null,
	},
]

export const mockBootstrapData: BootstrapData = {
	teams: mockTeams,
	events: [
		{
			id: 1,
			name: 'Gameweek 1',
			is_current: true,
			is_next: false,
			deadline_time: '2024-08-16T18:30:00Z',
			average_entry_score: 0,
			is_finished: false,
			highest_scoring_entry: null,
			most_captained: null,
		},
		{
			id: 2,
			name: 'Gameweek 2',
			is_current: false,
			is_next: true,
			deadline_time: '2024-08-23T18:30:00Z',
			average_entry_score: 0,
			is_finished: false,
			highest_scoring_entry: null,
			most_captained: null,
		},
		{
			id: 3,
			name: 'Gameweek 3',
			is_current: false,
			is_next: false,
			deadline_time: '2024-08-30T18:30:00Z',
			average_entry_score: 0,
			is_finished: false,
			highest_scoring_entry: null,
			most_captained: null,
		},
	],
	elements: [],
	element_types: [],
	game_settings: {
		transfers_limit: 1,
		chips: [],
	},
	total_players: 0,
}
